const Questions_array = [
    {
      id: 1,
      question: "What is your smoking status?",
      optionA: "Non-Smoker",
      optionB: "Occassional",
      optionC: "Regular",
      optionD: "Heavy Smoker",
    },
    {
      id: 2,
      question: "How often do you engage in exercise or physical activities?",
      optionA: "Non Smoker",
      optionB: "Occassional",
      optionC: "Regular",
      optionD: "Heavy Smoker",
    },
    {
      id: 3,
      question: "What is the largest mammal in the world?",
      optionA: "Elephant",
      optionB: "Whale Shark",
      optionC: "Blue Whale",
      optionD: "Giraffe",
    },
    {
      id: 4,
      question: "In which year did Christopher Columbus reach the Americas?",
      optionA: "1492",
      optionB: "1588",
      optionC: "1620",
      optionD: "1776",
    },
    {
      id: 5,
      question: "Which programming language is often used for web development?",
      optionA: "Java",
      optionB: "Python",
      optionC: "HTML",
      optionD: "Swift",
    },
    {
      id: 6,
      question: "What is the largest ocean on Earth?",
      optionA: "Atlantic Ocean",
      optionB: "Indian Ocean",
      optionC: "Arctic Ocean",
      optionD: "Pacific Ocean",
    },
    {
      id: 7,
      question: "Who wrote 'Romeo and Juliet'?",
      optionA: "Charles Dickens",
      optionB: "William Shakespeare",
      optionC: "Jane Austen",
      optionD: "Homer",
    },
    {
      id: 8,
      question: "Which country is known as the 'Land of the Rising Sun'?",
      optionA: "China",
      optionB: "Japan",
      optionC: "South Korea",
      optionD: "Thailand",
    },
    {
      id: 9,
      question: "What is the powerhouse of the cell?",
      optionA: "Nucleus",
      optionB: "Mitochondria",
      optionC: "Endoplasmic Reticulum",
      optionD: "Ribosome",
    },
    {
      id: 10,
      question: "Which famous scientist developed the theory of relativity?",
      optionA: "Isaac Newton",
      optionB: "Galileo Galilei",
      optionC: "Albert Einstein",
      optionD: "Niels Bohr",
    },
  ];

  export default Questions_array;