const Questions_array = [
    {
      id: 1,
      question: "What is your smoking status?",
      optionA: "Non-Smoker",
      optionB: "Occassional",
      optionC: "Regular",
      optionD: "Heavy Smoker",
    },
    {
      id: 2,
      question: "How often do you engage in exercise or physical activities?",
      optionA: "Never",
      optionB: "Occassional",
      optionC: "Regular(3-4 days a week)",
      optionD: "Daily",
    },
    {
      id: 3,
      question: "What is your Marital Status?",
      optionA: "Single",
      optionB: "Married",
      optionC: "Prefer not to say",
    //   optionD: "Giraffe",
    },
    {
      id: 4,
      question: "Do you consume alcohol on a regular basis?",
      optionA: "Yes",
      optionB: "No",
    //   optionC: "1620",
    //   optionD: "1776",
    },
    {
      id: 5,
      question: "What is your type of Residence?",
      optionA: "Rural",
      optionB: "Urban",
    //   optionC: "HTML",
    //   optionD: "Swift",
    },
    {
      id: 6,
      question: "Don you have a previous stroke history",
      optionA: "Yes",
      optionB: "No",
    //   optionC: "Arctic Ocean",
    //   optionD: "Pacific Ocean",
    },
    {
      id: 7,
      question: "Who wrote 'Romeo and Juliet'?",
      optionA: "Charles Dickens",
      optionB: "William Shakespeare",
      optionC: "Jane Austen",
      optionD: "Homer",
    },
    {
      id: 8,
      question: "Which country is known as the 'Land of the Rising Sun'?",
      optionA: "China",
      optionB: "Japan",
      optionC: "South Korea",
      optionD: "Thailand",
    },
    {
      id: 9,
      question: "What is the powerhouse of the cell?",
      optionA: "Nucleus",
      optionB: "Mitochondria",
      optionC: "Endoplasmic Reticulum",
      optionD: "Ribosome",
    },
    {
      id: 10,
      question: "Which famous scientist developed the theory of relativity?",
      optionA: "Isaac Newton",
      optionB: "Galileo Galilei",
      optionC: "Albert Einstein",
      optionD: "Niels Bohr",
    },
  ];

  export default Questions_array;